# Generated by Django 5.2.3 on 2025-06-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='regiao_estudo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade_curso',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
