# Generated by Django 5.2.3 on 2025-07-01 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_alter_pessoa_options_remove_pessoa_regiao_estudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
