# Generated by Django 5.2.3 on 2025-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0003_pessoa_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cidade_curso',
            field=models.CharField(max_length=100),
        ),
    ]
